### ISSUE TITLE
`skip_untranslated_strings` downloads empty keys

### ISSUE THREAD

**Issue by barrerajl** [crowdin/crowdin-cli#428]
**Describe the bug**
Downloading any language, when the key is not translated yet instead of skipping the key completely it will download it and put and empty string:

```
"translation-key": "",
```

**To Reproduce**
1. Configuration file: 
```
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_AUTH_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [{
  "source": "app/javascript/react/features/localization/locales/en.json",
  "dest": "/project/%original_file_name%",
  "translation": "%original_path%/%two_letters_code%.json",
  "skip_untranslated_strings": true
}, {
  "source": "config/locales/en.yml",
  "dest": "/project/%original_file_name%",
  "translation": "%original_path%/%two_letters_code%.yml",
  "skip_untranslated_strings": true
}]
```
2. Execute CLI command: `crowdin download --config .crowdin/crowdin.yml`
3. See an error

**Expected behavior**
There should not be any empty key in the downloaded file.

**Environment:**
 - OS: Ubuntu
 - Version 20.04.3 LTS

**Screenshots**

**Additional context**

**Comment by TaniaMal** [comment]
Hi @barrerajl!

Could you please send us the link to your project in Crowdin?

**Comment by barrerajl** [comment]
@TaniaMal
https://crowdin.com/project/hopin

**Comment by barrerajl** [comment]
@TaniaMal any updates?

**Comment by ira-sem** [comment]
Hi @barrerajl ! Sorry for the delay! Still checking on my side. Tried to reproduce but no luck, got everything on export as expected. Will keep you posted

**Comment by SamPersson** [comment]
We have the same issue with .json-files. In for example .resx-files in the same project untranslated strings are skipped as configured.

**Comment by ira-sem** [comment]
@SamPersson @barrerajl would it be possible to share the examples of the source files with us on support@crowdin.com?ans also specify there a project name

**Comment by TrixterTheTux** [comment]
Any news on this? Able to reproduce this with https://crowdin.com/project/wisp-game-panel/ (ID 502434) inside of https://github.com/wisp-gg/frontend using `crowdin download -b master`. Using Crowdin CLI installed through homebrew on Apple, version 3.7.8.

**Comment by zozulka** [comment]
We have already connected a processor to your project (ID 502434). It should resolve the issue. Could you please try again and tell us about the result?

**Comment by TrixterTheTux** [comment]
Thank you for the quick response! Just tested it, and the issue still happens.

**Comment by zozulka** [comment]
We will double-check everything from our side and come back to you with updates.

**Comment by zozulka** [comment]
Hi @TrixterTheTux. We have checked everything from our side and seems the issue should be resolved now. If it still persists, could you please specify the name of the file and the language where it occurs?

**Comment by TrixterTheTux** [comment]
I can see it working now - thank you!

**Comment by zozulka** [comment]
Dear @TrixterTheTux,
You are always welcome :)

**Comment by elvis-pereira** [comment]
I'm still having this exact same problem, tried to update my config file to use `skip_untranslated_strings`, but I'm getting empty strings instead when I tested running `crowdin download -b master`

Crowdin CLI version 3.7.8 (installed though NPM/PNPM) on linux.

GitLab repository: https://gitlab.com/fvtt-brasil/pf2e
Crowdin project: https://fvtt.crowdin.com/pf2e

`crowdin.yml` file:

```yml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://fvtt.crowdin.com

preserve_hierarchy: false

commit_message: "chore(crowdin): new translations %original_file_name% from Crowdin"
append_commit_message: false

files:
  [
    {
      source: /pf2e_pt-BR/lang/en/*.json,
      translation: /pf2e_pt-BR/lang/%locale%/compendium/pf2e.%original_file_name%,
      ignore: [/pf2e_pt-BR/lang/en/en.json, /pf2e_pt-BR/lang/en/re-en.json],
      skip_untranslated_strings: true
    },
    {
      source: /pf2e_pt-BR/lang/en/en.json,
      translation: /pf2e_pt-BR/lang/%locale%/system.json,
      skip_untranslated_strings: true
    },
    {
      source: /pf2e_pt-BR/lang/en/re-en.json,
      translation: /pf2e_pt-BR/lang/%locale%/rules-elements.json,
      skip_untranslated_strings: true
    },
  ]
```
