### ISSUE TITLE
Cannot deserialize value of type when using --verbose flag

### ISSUE THREAD

**Issue by NogaMan** [crowdin/crowdin-cli#925]
**Describe the bug**
I run `npx crowdin pre-translate --method=ai --ai-prompt=2 --plain --verbose --translate-untranslated-only --branch=racom-gnu-tolpu`

getting

```
❌ Error from server: <Code: <empty_code>, Message: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Integer>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"{"data":{"languages":[{"id":"es","files":[{"id":1991,"statistics":{"phrases":0,"words":0}},{"id":1989,"statistics":{"phrases":0,"words":0}},{"id":1987,"statistics":{"phrases":0,"words":0}},{"id":1985,"statistics":{"phrases":0,"words":0}},{"id":1983,"statistics":{"phrases":0,"words":0}},{"id":1981,"statistics":{"phrases":0,"words":0}},{"id":1885,"statistics":{"phrases":0,"words":0}},{"id":1931,"statistics":{"phrases":0,"words":0}},{"id":1923,"statistics":{"phrases":0,"words":0}},{"id":1889,"stati"[truncated 756 chars]; line: 1, column: 593] (through reference chain: com.crowdin.client.translations.model.PreTranslationReportResponseObject["data"]->com.crowdin.client.translations.model.PreTranslationReportResponse["languages"]->java.util.ArrayList[0]->com.crowdin.client.translations.model.PreTranslationReportResponse$TargetLanguage["skipped"])>
```

**To Reproduce**
Actually I have no idea, try to reproduce it yourself or maybe search through your logs. But I think it is connected to the newly added `--verbose` flag

**Expected behavior**
No error

**Environment:**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 18.04]

**Screenshots**

![Image](https://github.com/user-attachments/assets/715014e4-e920-4af9-b450-f0862ce05582)

**Additional context**

**Comment by andrii-bodnar** [comment]
Hi @NogaMan, thanks for reporting this!

It's definitely related to the latest release. I think that the root issue is in the [crowdin-api-client-java](https://github.com/crowdin/crowdin-api-client-java) which apparently can't deserialize the response it got from the API.

**Comment by andrii-bodnar** [comment]
For reference - https://github.com/crowdin/crowdin-api-client-java/pull/320

**Comment by innomaxx** [comment]
@NogaMan could you pls provide us the API response's JSON from Crowdin API Tool after executing this CLI Tool command again? Seems like this deserialization issue is related to `PreTranslationReportResponse.languages[i].skipped` field

**Comment by NogaMan** [comment]
@innomaxx, unfortunately I'm not using the verbose flag anymore on CI, where the error was happening sometimes. It does not reproduce stably

**Comment by andrii-bodnar** [comment]
Fixed in [4.9.0](https://github.com/crowdin/crowdin-cli/releases/tag/4.9.0)

**Comment by NogaMan** [comment]
@andrii-bodnar the issue still happens sometimes even on version 4.9.1:
`npx crowdin pre-translate --method=ai --ai-prompt=2 --plain --verbose --translate-untranslated-only --branch="${BRANCH_NAME}"`

```
Error from server: <Code: <empty_code>, Message: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Integer>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"{"data":{"languages":[{"id":"fr","files":[{"id":45481,"statistics":{"phrases":17,"words":316}},{"id":45469,"statistics":{"phrases":17,"words":316}},{"id":45419,"statistics":{"phrases":17,"words":316}},{"id":45417,"statistics":{"phrases":17,"words":316}},{"id":45415,"statistics":{"phrases":17,"words":316}},{"id":45413,"statistics":{"phrases":17,"words":316}}],"skipped":[],"skippedQaCheckCategories":[]},{"id":"es","files":[{"id":45481,"statistics":{"phrases":17,"words":316}},{"id":45469,"statistic"[truncated 2232 chars]; line: 1, column: 372] (through reference chain: com.crowdin.client.translations.model.PreTranslationReportResponseObject["data"]->com.crowdin.client.translations.model.PreTranslationReportResponse["languages"]->java.util.ArrayList[0]->com.crowdin.client.translations.model.PreTranslationReportResponse$TargetLanguage["skipped"])>
```
